apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::217698349416:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BBY5I9AXT9PZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::217698349416:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T00:16:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1807"
  uid: e62f8b26-c219-4b7a-88e1-f1a07a8b0b88
